language: node_js
node_js: stable
branches:
  only:
  - master
before_install:
- export TZ='Asia/Shanghai'
- npm install hexo-cli -g
install:
- npm install
script:
- hexo cl
- hexo g
after_script:
- git config --global user.name "Ethan Xia"
- git config --global user.email "sanhust@gmail.com"
- sed -i "s~git@github.com:~https://${GH_TOKEN}:x-oauth-basic@github.com/~" _config.yml
- hexo d
